### ISSUE TITLE
AWS Cognito fails to parse the metadata file/URL

### ISSUE THREAD

**Issue by digzapcg** [devkiran/mock-saml#103]
Unable to unmarshall metadata

**Comment by deepakprabhakara** [comment]
Thanks for reporting @digzapcg, are there any details on why the parsing fails in AWS Cognito?

**Comment by digzapcg** [comment]
Hey @deepakprabhakara , I couldn't find much info on the cognito console except for 
1. when we provide the URL we get this error
![image](https://user-images.githubusercontent.com/59307746/201258619-524edb1c-6db6-4a91-901e-cacd7d90728d.png)
2. when we provide the file we get this error
![image](https://user-images.githubusercontent.com/59307746/201258776-aa9034ce-73a4-4f07-abcd-5422abc59917.png)

**Comment by deepakprabhakara** [comment]
Aah looks like AWS Cognito is looking for the XML prefixes, thanks @digzapcg.

**Comment by deepakprabhakara** [comment]
https://github.com/boxyhq/mock-saml/pull/104 should potentially fix this issue

**Comment by deepakprabhakara** [comment]
@digzapcg The new version is out with a potential fix, could you please try and let me know?

**Comment by deepakprabhakara** [comment]
@digzapcg Closing this, please reopen if it's not fixed yet.
