### ISSUE TITLE
Will ARM architecture be available for docker installation?

### ISSUE THREAD

**Issue by carbonrim** [devkiran/mock-saml#126]
I'm trying to mock SAML in my project and I was thinking to use BoxyHQ Mock Saml, but docker installation process ended up with
 
`Status: Downloaded newer image for boxyhq/mock-saml:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

Are you going to prepare docker image for ARM architecture?

**Comment by deepakprabhakara** [comment]
Thanks for reporting this issue @carbonrim, we'll look into supporting the ARM arch. Will provide an ETA soon.

**Comment by deepakprabhakara** [comment]
@carbonrim v 1.0.7 has the arm64 arch, thanks again.
