### ISSUE TITLE
automated login flow

### ISSUE THREAD

**Issue by EugenMayer** [devkiran/mock-saml#155]
We want to use the mocker to entirely automate the login process. Thus we use a combination of mockMvc / resttempalte to

1. get the redirect including the SAMLrequest parameter (302 based, redirect based)
2. call that sso url via rest template
3. (2) will offer us some kind of either redirect or login form to login with the user (since the request / client is yet not authenicated
4. we would like to post some kind of form-data request via restTemplate to that form, to authenticate the user and retrieve the session cookie
5. use the target redirect from d (to the ACS) and follow that redirect using mockMVC - retrieve and ensure the user is logged in

This would test the entire SAML flow without any e2e testing tool and ensure the configuration/filter/provider and so forth are all correctly setup (thats the motivation / value).

Could you give us a hint how to do the part '4.' (anything else is no issue). 

- we assume the SAMLrequest id needs to be part of that post (context) so the SAMLresponse can be created
- which endpoint to use?
-  what form fields to set (should we just reverse engeneer the fields of the mocker login form?)

If you could share some ideas, this would be awesome!

**Comment by deepakprabhakara** [comment]
If you are doing this you might not even need Mock SAML, just take the code we use to generate the samlresponse and generate your own. The other option is to use Mock SAML and a headless browser

**Comment by EugenMayer** [comment]
i understand the alternatives.

Are there any technical issues why we would not be able to simulate the form post via client?

- is there a lot of Javascript involved (crypto)?
- CSRF token (which we would need to parse from the html first ,which is not too hard)

Could you elaborate, if possible, what the technical reason might be to not being able to simply use a webclient to simulate the headless browser?

**Comment by deepakprabhakara** [comment]
I don't see any technical issues, the form submission is straightforward using a bit of js and HTML.

**Comment by EugenMayer** [comment]
We decided to move away from mock-saml since the effort to implement the automated test against this mocker matches the effort to use an okta developer account and use a real world implementation for the integration tests - which is even better then a synthetic test against a mocker when having the same effort. Beside that, okta offers way better error handling, configuration and documentation (and supports all the opensaml4 protocols), and also API driven authentication.

In the end, it seems to be not practical to implement against the specific mock-saml island.

If we are going to need a mocker for saml IT tests further on, we will look at `saml-idp`- that one supports SAMLResponses without requiring an authentication, which is more what we would have expected of a mocker in the first place (IMHO).

I guess we seem to not have found the purpose of mock-saml yet, maybe this happens at a later point. Thank you for your effort and insight!

**Comment by deepakprabhakara** [comment]
@EugenMayer Makes sense. The main motivation and use for Mock SAML was for our public demo where using Okta is not practical since we need to get users to login to an IdP to experience the demo.
