### ISSUE TITLE
The ACS URL is down?

### ISSUE THREAD

**Issue by Matheus-H-B** [devkiran/mock-saml#293]
I've been trying to test the IdP Login since yesterday, but it keeps loading infinitely because apparently the ACS URL (https://jackson-demo.boxyhq.com/) is offline. Any predictions of normality?

**Comment by deepakprabhakara** [comment]
Thanks for reporting this, just restarted the service. Looks like there was a socket hangup so it felt like the service was still running, we'll add an alert for this.

**Comment by Matheus-H-B** [comment]
@deepakprabhakara Thank you!
