### ISSUE TITLE
Problems integrating with Keycloak

### ISSUE THREAD

**Issue by Matheus-H-B** [devkiran/mock-saml#294]
I'm trying to integrate Mock SAML into my Keycloak application.

I am downloading the metadata file available on the website and importing it into my Keycloak using the flow:
Identity Providers > Add provider > SAML v2.0 > Disable "Use entity descriptor" and import the XML file that I downloaded from Mock SAML.

However, when I try to log in, I get the login timeout message.

![Captura de Tela 2023-09-12 às 19 23 08](https://github.com/boxyhq/mock-saml/assets/113945653/dae06601-e8b6-46ab-84e6-2463f72debfd)

Searching the internet, I saw cases where there was a time difference on the Keycloak server caused by Docker, and people solved it by increasing the time in "Allowed clock skew", in Keycloak. However, I have already closed and opened my Docker several times, I have tried different values in "Allowed clock skew" but the problem persists.

![image](https://github.com/boxyhq/mock-saml/assets/113945653/f7165fab-b3ff-440d-8926-c41e259f1fbf)

Has anyone ever experienced this? Does anyone know what the problem could be?

My Keycloak version is 21.1.2

**Comment by niwsa** [comment]
@Matheus-H-B I am able to reproduce this issue. We will look into it and let you know.

**Comment by deepakprabhakara** [comment]
Fixed in v1.1.5
